/**
 * One-off generator: turns the deterministic seedDemoData() dataset into a SQL
 * seed file for the shared, read-only "Northstar" demo organization in Supabase.
 * Run with: npx tsx scripts/generate-demo-seed-sql.ts > supabase/migrations/0004_seed_demo.sql
 */
import { randomUUID } from 'node:crypto'
import { seedDemoData } from '../src/data/seed/generate'
import { DEMO_ORGANIZATION_ID } from '../src/lib/constants'

const DEMO_ORG_ID = DEMO_ORGANIZATION_ID

function sqlString(value: string | null | undefined): string {
  if (value === null || value === undefined) return 'null'
  return `'${value.replace(/'/g, "''")}'`
}


const dataset = seedDemoData()

const personIdMap = new Map<string, string>()
for (const p of dataset.people) personIdMap.set(p.id, randomUUID())

const skillIdMap = new Map<string, string>()
for (const s of dataset.skills) skillIdMap.set(s.id, randomUUID())

const teamIdMap = new Map<string, string>()
for (const t of dataset.teams) teamIdMap.set(t.id, randomUUID())

const sourceIdMap = new Map<string, string>()
for (const s of dataset.sources) sourceIdMap.set(s.id, randomUUID())

const lines: string[] = []
lines.push('-- Generated by scripts/generate-demo-seed-sql.ts — do not edit by hand.')
lines.push('-- Seeds the shared, read-only "Northstar" demo organization.')
lines.push('')
lines.push(
  `insert into organizations (id, name, industry, size, is_demo) values (${sqlString(DEMO_ORG_ID)}, ${sqlString(dataset.organization.name)}, ${sqlString(dataset.organization.industry)}, ${dataset.organization.size}, true);`,
)
lines.push('')

// People (two passes: insert without manager_id first, then set it, since
// managers are people too and may be inserted after their reports).
lines.push('-- People')
for (const p of dataset.people) {
  const id = personIdMap.get(p.id)
  lines.push(
    `insert into people (id, organization_id, first_name, last_name, job_title, department, location, country, bio, start_date, status, email, avatar) values (${sqlString(id)}, ${sqlString(DEMO_ORG_ID)}, ${sqlString(p.firstName)}, ${sqlString(p.lastName)}, ${sqlString(p.jobTitle)}, ${sqlString(p.department)}, ${sqlString(p.location)}, ${sqlString(p.country)}, ${sqlString(p.bio)}, ${sqlString(p.startDate)}, ${sqlString(p.status)}, ${sqlString(p.email)}, ${sqlString(p.avatar)});`,
  )
}
lines.push('')
lines.push('-- Manager relationships')
for (const p of dataset.people) {
  if (!p.managerId) continue
  const id = personIdMap.get(p.id)
  const managerId = personIdMap.get(p.managerId)
  lines.push(`update people set manager_id = ${sqlString(managerId)} where id = ${sqlString(id)};`)
}
lines.push('')

// Skills
lines.push('-- Skills')
for (const s of dataset.skills) {
  const id = skillIdMap.get(s.id)
  lines.push(
    `insert into skills (id, organization_id, name, category, description) values (${sqlString(id)}, ${sqlString(DEMO_ORG_ID)}, ${sqlString(s.name)}, ${sqlString(s.category)}, ${sqlString(s.description)});`,
  )
}
lines.push('')

// Person skills
lines.push('-- Person skills')
for (const ps of dataset.personSkills) {
  const personId = personIdMap.get(ps.personId)
  const skillId = skillIdMap.get(ps.skillId)
  lines.push(
    `insert into person_skills (organization_id, person_id, skill_id, level, years_experience, source) values (${sqlString(DEMO_ORG_ID)}, ${sqlString(personId)}, ${sqlString(skillId)}, ${sqlString(ps.level)}, ${ps.yearsExperience}, ${sqlString(ps.source)});`,
  )
}
lines.push('')

// Teams
lines.push('-- Teams')
for (const t of dataset.teams) {
  const id = teamIdMap.get(t.id)
  const managerId = t.managerId ? personIdMap.get(t.managerId) : null
  lines.push(
    `insert into teams (id, organization_id, name, description, manager_id) values (${sqlString(id)}, ${sqlString(DEMO_ORG_ID)}, ${sqlString(t.name)}, ${sqlString(t.description)}, ${sqlString(managerId)});`,
  )
}
lines.push('')

// Person teams
lines.push('-- Person teams')
for (const pt of dataset.personTeams) {
  const personId = personIdMap.get(pt.personId)
  const teamId = teamIdMap.get(pt.teamId)
  lines.push(
    `insert into person_teams (organization_id, person_id, team_id) values (${sqlString(DEMO_ORG_ID)}, ${sqlString(personId)}, ${sqlString(teamId)});`,
  )
}
lines.push('')

// Connections
lines.push('-- Connections')
for (const c of dataset.connections) {
  const a = personIdMap.get(c.personAId)
  const b = personIdMap.get(c.personBId)
  lines.push(
    `insert into connections (organization_id, person_a_id, person_b_id, type, strength, source) values (${sqlString(DEMO_ORG_ID)}, ${sqlString(a)}, ${sqlString(b)}, ${sqlString(c.type)}, ${c.strength}, ${sqlString(c.source)});`,
  )
}
lines.push('')

// Sources
lines.push('-- Sources (integrations)')
for (const s of dataset.sources) {
  const id = sourceIdMap.get(s.id)
  lines.push(
    `insert into sources (id, organization_id, type, name, status, last_sync_at) values (${sqlString(id)}, ${sqlString(DEMO_ORG_ID)}, ${sqlString(s.type)}, ${sqlString(s.name)}, ${sqlString(s.status)}, ${s.lastSyncAt ? sqlString(s.lastSyncAt) : 'null'});`,
  )
}

console.log(lines.join('\n'))
